# Generated by Django 5.1.4 on 2024-12-08 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SerVivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zoologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('servivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Zoologico1.servivo')),
                ('contador', models.IntegerField(default=0)),
                ('edad', models.IntegerField()),
                ('nombre_cientifico', models.CharField(max_length=255)),
                ('peso', models.FloatField()),
                ('tipo_dieta', models.CharField(choices=[('CARNIVORO', 'Carnívoro'), ('HERVIVORO', 'Hervívoro'), ('OMNIVORO', 'Omnívoro')], default='OMNIVORO', max_length=20)),
                ('tipo_cuerpo', models.CharField(choices=[('INVERTEBRADO', 'Invertebrado'), ('VERTEBRADO', 'Vertebrado')], default='VERTEBRADO', max_length=20)),
                ('estado', models.CharField(choices=[('COMIENDO', 'Comiendo'), ('DORMIDO', 'Dormido'), ('ENFERMO', 'Enfermo'), ('ESTRESADO', 'Estresado'), ('HAMBRIENTO', 'Hambriento'), ('HERIDO', 'Herido'), ('NORMAL', 'Normal')], default='NORMAL', max_length=20)),
            ],
            bases=('Zoologico1.servivo',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Zoologico1.persona')),
            ],
            bases=('Zoologico1.persona',),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Zoologico1.persona')),
                ('nombre_cliente', models.CharField(max_length=250)),
                ('identificacion', models.IntegerField()),
                ('salario', models.FloatField()),
            ],
            bases=('Zoologico1.persona',),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle_principal', models.CharField(max_length=255)),
                ('calle_secundaria', models.CharField(max_length=255)),
                ('referencia', models.TextField()),
                ('zoologico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direccion', to='Zoologico1.zoologico')),
            ],
        ),
        migrations.CreateModel(
            name='Jaula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField()),
                ('contador', models.IntegerField(default=0)),
                ('esta_limpio', models.BooleanField(default=True)),
                ('numero_jaula', models.CharField(max_length=20)),
                ('zona', models.CharField(choices=[('ESTE', 'Este'), ('NORTE', 'Norte'), ('OESTE', 'Oeste'), ('SUR', 'Sur')], default='NORTE', max_length=20)),
                ('animales', models.ManyToManyField(related_name='jaulas', to='Zoologico1.animal')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField()),
                ('fecha', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_medico', to='Zoologico1.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField()),
                ('numero', models.IntegerField()),
                ('valor', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='Zoologico1.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Zoologico1.empleado')),
            ],
            bases=('Zoologico1.empleado',),
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Zoologico1.empleado')),
            ],
            bases=('Zoologico1.empleado',),
        ),
        migrations.CreateModel(
            name='PersonalAdministrativo',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Zoologico1.empleado')),
            ],
            bases=('Zoologico1.empleado',),
        ),
        migrations.CreateModel(
            name='PersonalLimpieza',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Zoologico1.empleado')),
            ],
            bases=('Zoologico1.empleado',),
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Zoologico1.empleado')),
                ('especialidad', models.CharField(max_length=255)),
            ],
            bases=('Zoologico1.empleado',),
        ),
    ]
