# Generated by Django 5.1.4 on 2024-12-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoologico1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
