# Generated by Django 5.1.4 on 2024-12-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoologico1', '0002_persona_apellido_persona_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='correo',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
