# Generated by Django 5.1.4 on 2024-12-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoologico1', '0003_persona_correo_persona_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='contador',
        ),
        migrations.RemoveField(
            model_name='jaula',
            name='contador',
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
