# Generated by Django 5.1.4 on 2024-12-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoologico1', '0004_remove_animal_contador_remove_jaula_contador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='nombre_cliente',
        ),
        migrations.AddField(
            model_name='guia',
            name='clientes',
            field=models.ManyToManyField(related_name='guias', to='Zoologico1.cliente'),
        ),
    ]
