# Generated by Django 5.1.4 on 2024-12-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoologico1', '0005_remove_empleado_nombre_cliente_guia_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], max_length=10, null=True),
        ),
    ]
