# Generated by Django 5.1.4 on 2024-12-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoologico1', '0006_persona_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servivo',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
